### ISSUE TITLE
Implement flagd provider

### ISSUE THREAD

**Issue by toddbaert** [open-feature/dotnet-sdk-contrib#22] opened 2022-10-16 02:29 UTC
We need to build a gRPC flagd provider. This entails:

- Pulling the [proto](https://github.com/open-feature/schemas/blob/main/protobuf/schema/v1/schema.proto) definitions as a submodule
- building the c# bindings, likely using https://github.com/grpc/grpc-dotnet
- implementing the provider interface using the bindings above
- adding tests
- adding doc

See: https://github.com/open-feature/java-sdk-contrib/tree/main/providers/flagd

**Comment by benjiro** [comment] 2022-10-17 20:25
@toddbaert do you mind if I pick this one up?

**Comment by toddbaert** [comment] 2022-10-17 21:57
Not at all!

**Comment by toddbaert** [comment] 2022-10-17 21:59
The [JS impl](https://github.com/open-feature/js-sdk-contrib/tree/main/libs/providers/flagd) may also interest you. Feel free to ask myself @james-milligan for help.

**Comment by benjiro** [comment] 2022-10-30 11:44
@toddbaert sorry been pretty busy with work lately. I've done a basic implementation of flagd, still need to write tests, and add XML docs. You're welcome to contribute otherwise ill keep plugging away in my spare time.

**Comment by jonoabroad** [comment] 2022-12-13 17:37
Hey, there is a flagd provider in nuget on version 0.1.0 which links back to this repository.  Would it be the branch for this issue? 

It looks as thought the build is failing due to linting rules ?

Are there any missing commits, otherwise I may be able to find some time to plod away at it.

**Comment by beeme1mr** [comment] 2022-12-13 17:47
Hey @jonoabroad, the flagd provider in nuget is basically [a stub](https://github.com/open-feature/dotnet-sdk-contrib/tree/main/src/OpenFeature.Contrib.Providers.Flagd). It was intended to test the deployment process of the monorepo. @benjiro started the initial implementation in [this PR](https://github.com/open-feature/dotnet-sdk-contrib/pull/23) but you're welcome to contribute.

**Comment by benjiro** [comment] 2023-02-14 12:21
Thanks to @bacherfl, we now have a flagd provider. I'm going to close this we have the following tickets to advance the implementation further.

https://github.com/open-feature/dotnet-sdk-contrib/issues/35
https://github.com/open-feature/dotnet-sdk-contrib/issues/36

**Closed by benjiro** 2023-02-14 12:21 UTC
Labels: enhancement, roadmap

**Comment by toddbaert** [comment] 2023-02-14 13:17
@jonoabroad The flagd implementation is complete, FYI: https://github.com/open-feature/dotnet-sdk-contrib/tree/main/src/OpenFeature.Contrib.Providers.Flagd
